'use strict'

// @ts-check

export default [
  {
    id: 1161,
    thetvdb_id: 121361,
    imdb_id: 'tt0944947',
    title: 'Game of Thrones',
    original_title: 'Game of Thrones',
    description:
      "Seven noble families fight for control of the mythical land of Westeros. Friction between the houses leads to full-scale war. All while a very ancient evil awakens in the farthest north. Amidst the war, a neglected military order of misfits, the Night's Watch, is all that stands between the realms of men and the icy horrors beyond.",
    seasons: '8',
    seasons_details: [
      {
        number: 1,
        episodes: 10,
      },
      {
        number: 2,
        episodes: 10,
      },
      {
        number: 3,
        episodes: 10,
      },
      {
        number: 4,
        episodes: 10,
      },
      {
        number: 5,
        episodes: 10,
      },
      {
        number: 6,
        episodes: 13,
      },
      {
        number: 7,
        episodes: 9,
      },
      {
        number: 8,
        episodes: 7,
      },
    ],
    episodes: '79',
    followers: '220866',
    comments: '1380',
    similars: '42',
    characters: '79',
    creation: '2011',
    genres: ['Adventure', 'Drama', 'Fantasy'],
    length: '55',
    network: 'HBO',
    rating: 'TV-MA',
    status: 'Ended',
    language: 'en',
    notes: {
      total: 11120,
      mean: 4.76649999999999973709918776876293122768402099609375,
      user: 0,
    },
    in_account: false,
    images: {
      poster: '/posters/game-of-thrones.jpg',
    },
    aliases: {
      6432: 'Game of Thrones',
      14224: 'Juego de Tronos',
      1900: 'Le Trône De Fer',
    },
    social_links: [
      {
        type: 'facebook',
        external_id: 'GameOfThrones',
      },
      {
        type: 'twitter',
        external_id: 'GameOfThrones',
      },
      {
        type: 'instagram',
        external_id: 'gameofthrones',
      },
    ],
    user: {
      archived: false,
      favorited: true,
      remaining: 0,
      status: 0,
      last: 'S00E00',
      tags: null,
      next: {
        id: null,
        code: 'S00E00',
        date: null,
        title: null,
        image: null,
      },
      friends_watching: [],
    },
    next_trailer: '5PxLidxnAE8',
    resource_url: 'https://www.betaseries.com/serie/gameofthrones',
  },
  {
    id: 1275,
    thetvdb_id: 153021,
    imdb_id: 'tt1520211',
    title: 'The Walking Dead',
    original_title: 'The Walking Dead',
    description:
      'The world we knew is gone. An epidemic of apocalyptic proportions has swept the globe causing the dead to rise and feed on the living. In a matter of months society has crumbled. In a world ruled by the dead, we are forced to finally start living. Based on a comic book series of the same name by Robert Kirkman, this AMC project focuses on the world after a zombie apocalypse. The series follows a police officer, Rick Grimes, who wakes up from a coma to find the world ravaged with zombies. Looking for his family, he and a group of survivors attempt to battle against the zombies in order to stay alive.',
    seasons: '10',
    seasons_details: [
      {
        number: 1,
        episodes: 7,
      },
      {
        number: 2,
        episodes: 14,
      },
      {
        number: 3,
        episodes: 16,
      },
      {
        number: 4,
        episodes: 16,
      },
      {
        number: 5,
        episodes: 16,
      },
      {
        number: 6,
        episodes: 17,
      },
      {
        number: 7,
        episodes: 16,
      },
      {
        number: 8,
        episodes: 16,
      },
      {
        number: 9,
        episodes: 16,
      },
      {
        number: 10,
        episodes: 8,
      },
    ],
    episodes: '142',
    followers: '166478',
    comments: '1376',
    similars: '39',
    characters: '46',
    creation: '2010',
    genres: ['Adventure', 'Drama', 'Horror', 'Thriller'],
    length: '45',
    network: 'AMC',
    rating: 'TV-MA',
    status: 'Continuing',
    language: 'en',
    notes: {
      total: 6738,
      mean: 4.4551999999999996049382389173842966556549072265625,
      user: 0,
    },
    in_account: false,
    images: {
      poster: '/posters/the-walking-dead.jpg',
    },
    aliases: {
      1713: 'The Walking Dead',
      22242: 'The Walking Macarrones',
      22284: 'The Walking Monger',
      29147: 'TWD',
    },
    social_links: [
      {
        type: 'facebook',
        external_id: 'TheWalkingDeadAMC',
      },
      {
        type: 'twitter',
        external_id: 'WalkingDead_AMC',
      },
      {
        type: 'instagram',
        external_id: 'amcthewalkingdead',
      },
    ],
    user: {
      archived: false,
      favorited: false,
      remaining: 0,
      status: 0,
      last: 'S00E00',
      tags: null,
      next: {
        id: null,
        code: 'S00E00',
        date: null,
        title: null,
        image: null,
      },
      friends_watching: [],
    },
    next_trailer: 'R1v0uFms68U',
    resource_url: 'https://www.betaseries.com/serie/thewalkingdead',
  },
  {
    id: 481,
    thetvdb_id: 81189,
    imdb_id: 'tt0903747',
    title: 'Breaking Bad',
    original_title: 'Breaking Bad',
    description:
      "Walter White, a struggling high school chemistry teacher, is diagnosed with advanced lung cancer. He turns to a life of crime, producing and selling methamphetamine accompanied by a former student, Jesse Pinkman, with the aim of securing his family's financial future before he dies.",
    seasons: '5',
    seasons_details: [
      {
        number: 1,
        episodes: 12,
      },
      {
        number: 2,
        episodes: 13,
      },
      {
        number: 3,
        episodes: 13,
      },
      {
        number: 4,
        episodes: 13,
      },
      {
        number: 5,
        episodes: 17,
      },
    ],
    episodes: '68',
    followers: '126646',
    comments: '778',
    similars: '30',
    characters: '19',
    creation: '2008',
    genres: ['Crime', 'Drama', 'Suspense', 'Thriller'],
    length: '45',
    network: 'AMC',
    rating: 'TV-MA',
    status: 'Ended',
    language: 'en',
    notes: {
      total: 6930,
      mean: 4.779370000000000118234311230480670928955078125,
      user: 0,
    },
    in_account: false,
    images: {
      poster: '/posters/breaking-bad.jpg',
    },
    aliases: {
      1726: 'Breaking Bad',
      5119: 'Breaking Bad : Le Chimiste',
    },
    social_links: [
      {
        type: 'facebook',
        external_id: 'BreakingBad',
      },
      {
        type: 'twitter',
        external_id: 'BreakingBad_AMC',
      },
    ],
    user: {
      archived: false,
      favorited: false,
      remaining: 0,
      status: 0,
      last: 'S00E00',
      tags: null,
      next: {
        id: null,
        code: 'S00E00',
        date: null,
        title: null,
        image: null,
      },
      friends_watching: [],
    },
    next_trailer: '--z4YzxlT8o',
    resource_url: 'https://www.betaseries.com/serie/breakingbad',
  },
  {
    id: 196,
    thetvdb_id: 73762,
    imdb_id: 'tt0413573',
    title: "Grey's Anatomy",
    original_title: "Grey's Anatomy",
    description:
      'A drama centered on the personal and professional lives of five surgical interns and their supervisors.',
    seasons: '16',
    seasons_details: [
      {
        number: 1,
        episodes: 9,
      },
      {
        number: 2,
        episodes: 27,
      },
      {
        number: 3,
        episodes: 25,
      },
      {
        number: 4,
        episodes: 17,
      },
      {
        number: 5,
        episodes: 24,
      },
      {
        number: 6,
        episodes: 24,
      },
      {
        number: 7,
        episodes: 22,
      },
      {
        number: 8,
        episodes: 24,
      },
      {
        number: 9,
        episodes: 24,
      },
      {
        number: 10,
        episodes: 24,
      },
      {
        number: 11,
        episodes: 24,
      },
      {
        number: 12,
        episodes: 24,
      },
      {
        number: 13,
        episodes: 24,
      },
      {
        number: 14,
        episodes: 24,
      },
      {
        number: 15,
        episodes: 25,
      },
      {
        number: 16,
        episodes: 10,
      },
    ],
    episodes: '350',
    followers: '124188',
    comments: '423',
    similars: '43',
    characters: '56',
    creation: '2005',
    genres: ['Drama', 'Romance', 'Soap'],
    length: '45',
    network: 'ABC (US)',
    rating: 'TV-14',
    status: 'Continuing',
    language: 'en',
    notes: {
      total: 3375,
      mean: 4.47820000000000018047785488306544721126556396484375,
      user: 0,
    },
    in_account: false,
    images: {
      poster: '/posters/greys-anatomy.jpg',
    },
    aliases: {
      22525: 'Anatomía Anal',
      22500: 'Anatomía de Gays',
      13612: 'Anatomía de Grey',
      17375: "Dre Grey, leçons d'anatomie",
      5011: 'Dre Grey, leçons d’anatomie',
      1793: "Grey's Anatomy",
      20615: "Grey's Anatomy : A coeur ouvert",
      12104: 'Greys Anatomy',
    },
    social_links: [
      {
        type: 'facebook',
        external_id: 'GreysAnatomy',
      },
      {
        type: 'twitter',
        external_id: 'greysabc',
      },
      {
        type: 'instagram',
        external_id: 'greysabc',
      },
    ],
    user: {
      archived: false,
      favorited: false,
      remaining: 0,
      status: 0,
      last: 'S00E00',
      tags: null,
      next: {
        id: null,
        code: 'S00E00',
        date: null,
        title: null,
        image: null,
      },
      friends_watching: [],
    },
    next_trailer: null,
    resource_url: 'https://www.betaseries.com/serie/greysanatomy',
  },
  {
    id: 14,
    thetvdb_id: 80379,
    imdb_id: 'tt0898266',
    title: 'The Big Bang Theory',
    original_title: 'The Big Bang Theory',
    description:
      'A woman who moves into an apartment across the hall from two brilliant but socially awkward physicists shows them how little they know about life outside of the laboratory.',
    seasons: '12',
    seasons_details: [
      {
        number: 1,
        episodes: 17,
      },
      {
        number: 2,
        episodes: 23,
      },
      {
        number: 3,
        episodes: 23,
      },
      {
        number: 4,
        episodes: 24,
      },
      {
        number: 5,
        episodes: 24,
      },
      {
        number: 6,
        episodes: 24,
      },
      {
        number: 7,
        episodes: 24,
      },
      {
        number: 8,
        episodes: 24,
      },
      {
        number: 9,
        episodes: 24,
      },
      {
        number: 10,
        episodes: 24,
      },
      {
        number: 11,
        episodes: 24,
      },
      {
        number: 12,
        episodes: 25,
      },
    ],
    episodes: '280',
    followers: '121112',
    comments: '396',
    similars: '41',
    characters: '27',
    creation: '2007',
    genres: ['Comedy'],
    length: '25',
    network: 'CBS',
    rating: 'TV-14',
    status: 'Ended',
    language: 'en',
    notes: {
      total: 4523,
      mean: 4.55830000000000001847411112976260483264923095703125,
      user: 0,
    },
    in_account: false,
    images: {
      poster: '/posters/the-big-bang-theory.jpg',
    },
    aliases: {
      21429: 'Big Bang',
      1365: 'Big Bang Theory',
      22289: 'The Big Bang Anal',
      1933: 'The Big Bang Theory',
    },
    social_links: [
      {
        type: 'facebook',
        external_id: 'TheBigBangTheory',
      },
      {
        type: 'twitter',
        external_id: 'bigbangtheory',
      },
      {
        type: 'instagram',
        external_id: 'bigbangtheory_cbs',
      },
    ],
    user: {
      archived: false,
      favorited: false,
      remaining: 0,
      status: 0,
      last: 'S00E00',
      tags: null,
      next: {
        id: null,
        code: 'S00E00',
        date: null,
        title: null,
        image: null,
      },
      friends_watching: [],
    },
    next_trailer: null,
    resource_url: 'https://www.betaseries.com/serie/bigbangtheory',
  },
  {
    id: 8,
    thetvdb_id: 75760,
    imdb_id: 'tt0460649',
    title: 'How I Met Your Mother',
    original_title: 'How I Met Your Mother',
    description:
      'The year is 2030. Ted Mosby is relaying the story of how he met his wife to his daughter and son. The story starts in the year 2005, when then twenty-seven year old architect Ted was spurred on to want to get married after his best friends from his college days at Wesleyan, lawyer Marshall Eriksen, who was his roommate at the time and kindergarten teacher Lily Aldrin, got engaged after nine years of dating each other. Ted\'s new quest in life was much to the dismay of his womanizing friend, Barney Stinson. But soon after Marshall and Lily\'s engagement, Ted believed that his life mate was going to be news reporter and aspiring news anchor Robin Scherbatsky, who, despite having had a romantic relationship with her after this time, ended up being who the kids know as their "Aunt" Robin. As Ted relays the story to his kids, the constants are that their Uncle Marshall, Aunt Lily, Uncle Barney and Aunt Robin are always in the picture and thus have something to do with how he got together with their mother.',
    seasons: '9',
    seasons_details: [
      {
        number: 1,
        episodes: 22,
      },
      {
        number: 2,
        episodes: 22,
      },
      {
        number: 3,
        episodes: 20,
      },
      {
        number: 4,
        episodes: 24,
      },
      {
        number: 5,
        episodes: 24,
      },
      {
        number: 6,
        episodes: 24,
      },
      {
        number: 7,
        episodes: 24,
      },
      {
        number: 8,
        episodes: 24,
      },
      {
        number: 9,
        episodes: 24,
      },
    ],
    episodes: '208',
    followers: '116807',
    comments: '489',
    similars: '52',
    characters: '16',
    creation: '2005',
    genres: ['Comedy', 'Romance'],
    length: '25',
    network: 'CBS',
    rating: 'TV-14',
    status: 'Ended',
    language: 'en',
    notes: {
      total: 6141,
      mean: 4.3374043315420944821880766539834439754486083984375,
      user: 0,
    },
    in_account: false,
    images: {
      poster: '/posters/how-i-met-your-mother.jpg',
    },
    aliases: {
      5117: "Comment je l'ai rencontrée",
      5118: 'Comment j’ai rencontré votre mère',
      15792: 'Cómo Conocí a Vuestra Madre',
      22556: 'Cómo Conocí a Vuestra Puta Madre',
      1554: 'How I Met Your Mother',
      19183: 'ママと恋に落ちるまで',
    },
    social_links: [],
    user: {
      archived: false,
      favorited: false,
      remaining: 0,
      status: 0,
      last: 'S00E00',
      tags: null,
      next: {
        id: null,
        code: 'S00E00',
        date: null,
        title: null,
        image: null,
      },
      friends_watching: [],
    },
    next_trailer: null,
    resource_url: 'https://www.betaseries.com/serie/himym',
  },
  {
    id: 26,
    thetvdb_id: 79349,
    imdb_id: 'tt0773262',
    title: 'Dexter',
    original_title: 'Dexter',
    description:
      "Dexter Morgan is a Miami-based blood splatter expert who doesn't just solve murders; he commits them too. In fact, he's a serial killer -- but he only murders the guilty, so he feels justified with his lifestyle choices. His policewoman sister and his cop co-workers have no idea Dexter lives a double life; however, adoptive father Harry knows his secret, and does, in fact, help Dexter hone his \"skills.\" It's a unique brand of justice for which charming Dexter feels a psychological hunger.",
    seasons: '8',
    seasons_details: [
      {
        number: 1,
        episodes: 12,
      },
      {
        number: 2,
        episodes: 12,
      },
      {
        number: 3,
        episodes: 12,
      },
      {
        number: 4,
        episodes: 13,
      },
      {
        number: 5,
        episodes: 12,
      },
      {
        number: 6,
        episodes: 12,
      },
      {
        number: 7,
        episodes: 12,
      },
      {
        number: 8,
        episodes: 12,
      },
    ],
    episodes: '97',
    followers: '115885',
    comments: '571',
    similars: '22',
    characters: '28',
    creation: '2006',
    genres: ['Crime', 'Drama', 'Mystery', 'Suspense', 'Thriller'],
    length: '50',
    network: 'Showtime',
    rating: 'TV-MA',
    status: 'Ended',
    language: 'en',
    notes: {
      total: 4832,
      mean: 4.54079999999999994741983755375258624553680419921875,
      user: 0,
    },
    in_account: false,
    images: {
      poster: '/posters/dexter.jpg',
    },
    aliases: {
      24022: 'canduterio',
      1457: 'Dexter',
    },
    social_links: [],
    user: {
      archived: false,
      favorited: false,
      remaining: 0,
      status: 0,
      last: 'S00E00',
      tags: null,
      next: {
        id: null,
        code: 'S00E00',
        date: null,
        title: null,
        image: null,
      },
      friends_watching: [],
    },
    next_trailer: null,
    resource_url: 'https://www.betaseries.com/serie/dexter',
  },
  {
    id: 744,
    thetvdb_id: 95491,
    imdb_id: 'tt1405406',
    title: 'The Vampire Diaries',
    original_title: 'The Vampire Diaries',
    description:
      'As the school year begins, Elena Gilbert is immediately drawn to a handsome and mysterious new student, Stefan Salvatore. Elena has no way of knowing that Stefan is a vampire struggling to live peacefully among humans, while his brother Damon is the embodiment of vampire violence and brutality.',
    seasons: '8',
    seasons_details: [
      {
        number: 1,
        episodes: 22,
      },
      {
        number: 2,
        episodes: 22,
      },
      {
        number: 3,
        episodes: 22,
      },
      {
        number: 4,
        episodes: 23,
      },
      {
        number: 5,
        episodes: 22,
      },
      {
        number: 6,
        episodes: 22,
      },
      {
        number: 7,
        episodes: 22,
      },
      {
        number: 8,
        episodes: 16,
      },
    ],
    episodes: '171',
    followers: '110295',
    comments: '791',
    similars: '69',
    characters: '42',
    creation: '2009',
    genres: ['Drama', 'Fantasy', 'Horror', 'Romance'],
    length: '45',
    network: 'The CW',
    rating: 'TV-PG',
    status: 'Ended',
    language: 'en',
    notes: {
      total: 3418,
      mean: 4.40369999999999972573050399660132825374603271484375,
      user: 0,
    },
    in_account: false,
    images: {
      poster: '/posters/the-vampire-diaries.jpg',
    },
    aliases: {
      13695: 'Crónicas vampíricas',
      5121: "Journal d'un vampire",
      22196: 'Journal d’un vampire',
      1675: 'The Vampire Diaries',
      13694: 'Vampire Diaries',
    },
    social_links: [
      {
        type: 'facebook',
        external_id: 'thevampirediaries',
      },
      {
        type: 'twitter',
        external_id: 'cwtvd',
      },
      {
        type: 'instagram',
        external_id: 'thecwtvd',
      },
    ],
    user: {
      archived: false,
      favorited: false,
      remaining: 0,
      status: 0,
      last: 'S00E00',
      tags: null,
      next: {
        id: null,
        code: 'S00E00',
        date: null,
        title: null,
        image: null,
      },
      friends_watching: [],
    },
    next_trailer: null,
    resource_url: 'https://www.betaseries.com/serie/vampirediaries',
  },
  {
    id: 12742,
    thetvdb_id: 305288,
    imdb_id: 'tt4574334',
    title: 'Stranger Things',
    original_title: 'Stranger Things',
    description:
      'Tribute to the classic supernatural mysteries of the 80s, "Stranger Things" is the story of a boy who disappears in the small town of Hawkins, Indiana, without a trace in 1983. In his desperate search, both his friends and family and the local sheriff are involved in an extraordinary enigma: top-secret experiments, terrifying paranormal forces and a very, very rare girl ...',
    seasons: '3',
    seasons_details: [
      {
        number: 1,
        episodes: 8,
      },
      {
        number: 2,
        episodes: 16,
      },
      {
        number: 3,
        episodes: 8,
      },
    ],
    episodes: '32',
    followers: '97471',
    comments: '252',
    similars: '14',
    characters: '18',
    creation: '2016',
    genres: ['Adventure', 'Drama', 'Fantasy', 'Horror', 'Mystery'],
    length: '50',
    network: 'Netflix',
    rating: 'TV-14',
    status: 'Continuing',
    language: 'en',
    notes: {
      total: 2406,
      mean: 4.6089000000000002188471626141108572483062744140625,
      user: 0,
    },
    in_account: false,
    images: {
      poster: '/posters/stranger-things.jpg',
    },
    aliases: {
      12042: 'Beyond Stranger Things',
      28178: 'El de las milfs, ponlo xD',
      9958: 'Montauk',
      28152: 'Stranger Dicks',
      9087: 'Stranger Things',
    },
    social_links: [
      {
        type: 'facebook',
        external_id: 'StrangerThingsTV',
      },
      {
        type: 'twitter',
        external_id: 'stranger_things',
      },
      {
        type: 'instagram',
        external_id: 'strangerthingstv',
      },
    ],
    user: {
      archived: false,
      favorited: false,
      remaining: 0,
      status: 0,
      last: 'S00E00',
      tags: null,
      next: {
        id: null,
        code: 'S00E00',
        date: null,
        title: null,
        image: null,
      },
      friends_watching: [],
    },
    next_trailer: null,
    resource_url: 'https://www.betaseries.com/serie/stranger-things',
  },
]
